# Generated by Django 2.0.3 on 2018-05-09 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talos_rest', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CryptoListenerModel',
        ),
    ]
