# Generated by Django 2.0.3 on 2018-04-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimepasswordcredential',
            name='is_activated',
            field=models.BooleanField(default=False),
        ),
    ]
