# Generated by Django 2.0.3 on 2018-04-15 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talos', '0003_principalprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneSMSValidationToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(editable=False, max_length=64, unique=True)),
                ('phone', models.CharField(max_length=255)),
                ('expires_at', models.DateTimeField(editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('principal', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
