# Generated by Django 2.0.3 on 2018-04-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talos', '0004_phonesmsvalidationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicidentity',
            name='email',
            field=models.CharField(default='default_email', max_length=255),
        ),
    ]
