# Generated by Django 2.0.3 on 2018-04-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talos', '0005_basicidentity_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonesmsvalidationtoken',
            name='salt',
            field=models.CharField(default='', max_length=64),
        ),
    ]
