# Generated by Django 2.0.3 on 2018-04-24 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talos', '0006_phonesmsvalidationtoken_salt'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='basicidentity',
            unique_together={('directory', 'email')},
        ),
    ]
