# Generated by Django 2.0.3 on 2018-04-25 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talos', '0007_auto_20180424_0932'),
        ('talos', '0007_auto_20180424_0752'),
    ]

    operations = [
    ]
